### ISSUE TITLE
Fix crash at opening WebView on Android 6.1

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/generika_android#31]

**Comment by grauwoelfchen** [comment]
It seems that `setProgress` does not exist on 6.0.1.

```txt
03-16 10:09:00.149 29126 29126 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setProgress(IZ)V in class Landroid/widget/ProgressBar; or its super classes (declaration of 'android.widget.ProgressBar' appears in /system/framework/framework.jar:classes2.dex)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at org.oddb.generika.WebViewActivity$1.onProgressChanged(WebViewActivity.java:138)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:45)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:81)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-16 10:09:00.149 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
...
```
