### ISSUE TITLE
App crashes every time I click on the Interaktion Button

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generika_android#63]
1. Start the App.
2. Click on "Interaktionen" Button
3. App crashes.

**Comment by zdavatz** [comment]
This is the Crash Log from my Phone
```
04-19 14:00:02.630  1452  2899 I ActivityManager: Start proc 11540:com.android.chrome:sandboxed_process0/u0i68 for webview_service org.oddb.generika/org.chromium.content.app.SandboxedProcessService0
04-19 14:00:02.800 11193 11193 E AndroidRuntime: Process: org.oddb.generika, PID: 11193
04-19 14:00:02.800 11193 11193 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.oddb.generika/org.oddb.generika.WebViewActivity}: java.lang.NullPointerException: Attempt to get length of null array
04-19 14:00:02.800 11193 11193 E AndroidRuntime:        at org.oddb.generika.WebViewActivity.buildUrl(WebViewActivity.java:268)
04-19 14:00:02.800 11193 11193 E AndroidRuntime:        at org.oddb.generika.WebViewActivity.onCreate(WebViewActivity.java:83)
04-19 14:00:02.804  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.WebViewActivity
04-19 14:00:02.807  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.MainActivity
04-19 14:00:02.817  1452  1523 I ActivityManager: Showing crash dialog for package org.oddb.generika u0
04-19 14:00:03.307  1452  1521 W ActivityManager: Activity pause timeout for ActivityRecord{e943735 u0 org.oddb.generika/.WebViewActivity t392 f}
04-19 14:00:11.951  1452  2899 I ActivityManager: Killing 11193:org.oddb.generika/u0a155 (adj 900): crash
04-19 14:00:12.000  1452  2899 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=org.oddb.generika cmp=org.oddb.generika/.MainActivity} from uid 10034
04-19 14:00:12.055  1452 20055 I ActivityManager: Start proc 11608:org.oddb.generika/u0a155 for activity org.oddb.generika/.MainActivity
04-19 14:00:15.412  1452 18015 I ActivityManager: START u0 {cmp=org.oddb.generika/.WebViewActivity (has extras)} from uid 10155
04-19 14:00:15.587  1452  2899 I ActivityManager: Start proc 11663:com.android.chrome:sandboxed_process0/u0i69 for webview_service org.oddb.generika/org.chromium.content.app.SandboxedProcessService0
04-19 14:00:23.528  1452  2962 W ActivityManager: Scheduling restart of crashed service org.oddb.generika/org.chromium.content.app.SandboxedProcessService0 in 1000ms
04-19 14:00:29.692  1452 18015 I ActivityManager: START u0 {cmp=org.oddb.generika/.WebViewActivity} from uid 10155
04-19 14:00:29.798 11608 11608 E AndroidRuntime: Process: org.oddb.generika, PID: 11608
04-19 14:00:29.798 11608 11608 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.oddb.generika/org.oddb.generika.WebViewActivity}: java.lang.NullPointerException: Attempt to get length of null array
04-19 14:00:29.798 11608 11608 E AndroidRuntime:        at org.oddb.generika.WebViewActivity.buildUrl(WebViewActivity.java:268)
04-19 14:00:29.798 11608 11608 E AndroidRuntime:        at org.oddb.generika.WebViewActivity.onCreate(WebViewActivity.java:83)
04-19 14:00:29.800  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.WebViewActivity
04-19 14:00:29.803  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.MainActivity
04-19 14:00:29.806  1452  1523 I ActivityManager: Showing crash dialog for package org.oddb.generika u0
04-19 14:00:30.302  1452  1521 W ActivityManager: Activity pause timeout for ActivityRecord{f0ac2bc u0 org.oddb.generika/.WebViewActivity t392 f}
04-19 14:00:30.992  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.WebViewActivity
04-19 14:00:30.993  1452  2899 W ActivityManager:   Force finishing activity org.oddb.generika/.MainActivity
04-19 14:00:31.031  1452  2899 I ActivityManager: Killing 11608:org.oddb.generika/u0a155 (adj 900): crash
04-19 14:03:50.495  1452  9407 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.oddb.generika/.MainActivity bnds=[643,108][849,400]} from uid 10026
04-19 14:03:50.504   540   540 E ANDR-IOP: IOP HAL: Received pkg_name = org.oddb.generika pid = -1
```

**Comment by zdavatz** [comment]
This is the crash from the Google Store Log
```
Heute, 14:59 in der App-Version 44
Xiaomi Mi A1 (tissot_sprout), 4096MB RAM, Android 8.0
Bericht 1 von 3

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2831)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2906)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1605)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:172)
  at android.app.ActivityThread.main (ActivityThread.java:6637)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: 
  at android.text.TextUtils.join (TextUtils.java:304)
  at org.oddb.generika.WebViewActivity.buildUrl (WebViewActivity.java:268)
  at org.oddb.generika.WebViewActivity.onCreate (WebViewActivity.java:83)
  at android.app.Activity.performCreate (Activity.java:6975)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2784)
```

**Comment by zdavatz** [comment]
![](https://i.imgur.com/ZNgqUFY.png) interaction button works well now!
