### ISSUE TITLE
App crashes after Scan on Android 14 SDK 34, Realm exception.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generika_android#92]
1. Open the App.
2. Scan a Barcode.
3. App crashes.
```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5815)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5854)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:69)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:60)
  at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem (TransactionExecutor.java:231)
  at android.app.servertransaction.TransactionExecutor.executeTransactionItems (TransactionExecutor.java:152)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:93)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2595)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loopOnce (Looper.java:232)
  at android.os.Looper.loop (Looper.java:317)
  at android.app.ActivityThread.main (ActivityThread.java:8592)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:580)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:878)
Caused by io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
  at io.realm.BaseRealm.checkAllowWritesOnUiThread (BaseRealm.java:553)
  at io.realm.Realm.executeTransaction (Realm.java:1629)
  at org.oddb.generika.data.DataManager$2.execute (DataManager.java:154)
  at org.oddb.generika.model.Retryable$-CC.withRetry (Retryable.java:55)
  at org.oddb.generika.model.Product.withRetry (Product.java:170)
  at org.oddb.generika.data.DataManager.addProduct (DataManager.java:149)
  at org.oddb.generika.MainActivity.onActivityResult (MainActivity.java:660)
  at android.app.Activity.internalDispatchActivityResult (Activity.java:9340)
  at android.app.Activity.dispatchActivityResult (Activity.java:9324)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5807)
```

**Comment by zdavatz** [comment]
Crash log from the device:
```
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

SystemUptimeMs: 3883685
Process: org.oddb.generika
PID: 6124
UID: 10297
Frozen: false
Flags: 0x20c8be44
Package: org.oddb.generika v59 (1.0.59)
Foreground: Yes
Process-Runtime: 9602
Build: google/akita/akita:14/AP2A.240905.003.A1/12234140:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9000, result=0, data=Intent { (has extras) }} to activity {org.oddb.generika/org.oddb.generika.MainActivity}: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5815)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5854)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:69)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:553)
	at io.realm.Realm.executeTransaction(Realm.java:1629)
	at org.oddb.generika.data.DataManager$2.execute(DataManager.java:154)
	at org.oddb.generika.model.Retryable$-CC.withRetry(Retryable.java:55)
	at org.oddb.generika.model.Product.withRetry(Product.java:170)
	at org.oddb.generika.data.DataManager.addProduct(DataManager.java:149)
	at org.oddb.generika.MainActivity.onActivityResult(MainActivity.java:660)
	at android.app.Activity.internalDispatchActivityResult(Activity.java:9340)
	at android.app.Activity.dispatchActivityResult(Activity.java:9324)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5807)
	... 14 more
```

**Comment by zdavatz** [comment]
`adb logcat` output
```
09-20 13:37:47.517 11744 11744 D SaveBarcodeImageTask: (onPostExecute) fullpath: /data/user/0/org.oddb.generika/files/barcodes/7680497710373-20240920113747.jpg
09-20 13:37:47.517 11744 11896 D BarcodeCaptureActivity: (onBarcodeDetected) filepath: /data/user/0/org.oddb.generika/files/barcodes/7680497710373-20240920113747.jpg
09-20 13:37:47.811  1489 11305 I Camera2ClientBase: ~Camera2ClientBase: Client object's dtor for Camera Id 0 completed. Client was: org.oddb.generika (PID 11744, UID 10301)
09-20 13:37:47.832 11744 11744 D SaveBarcodeImageTask: (onPostExecute) fullpath: /data/user/0/org.oddb.generika/files/barcodes/7680497710373-20240920113747.jpg
09-20 13:37:47.839 11744 11744 D MainActivity: (onActivityResult) filepath: /data/user/0/org.oddb.generika/files/barcodes/7680497710373-20240920113747.jpg
09-20 13:37:47.841 11744 11744 W System.err: 	at org.oddb.generika.data.DataManager$2.execute(DataManager.java:154)
09-20 13:37:47.841 11744 11744 W System.err: 	at org.oddb.generika.model.Retryable$-CC.withRetry(Retryable.java:55)
09-20 13:37:47.841 11744 11744 W System.err: 	at org.oddb.generika.model.Product.withRetry(Product.java:170)
09-20 13:37:47.841 11744 11744 W System.err: 	at org.oddb.generika.data.DataManager.addProduct(DataManager.java:149)
09-20 13:37:47.841 11744 11744 W System.err: 	at org.oddb.generika.MainActivity.onActivityResult(MainActivity.java:660)
09-20 13:37:47.843 11744 11744 E TransactionExecutor: tId:-150475194     Target activity: org.oddb.generika.MainActivity
09-20 13:37:47.843 11744 11744 E TransactionExecutor: tId:-150475194     Target activity: org.oddb.generika.MainActivity
09-20 13:37:47.843 11744 11744 E TransactionExecutor: tId:-150475194     Target activity: org.oddb.generika.MainActivity
09-20 13:37:47.845 11744 11744 E AndroidRuntime: Process: org.oddb.generika, PID: 11744
09-20 13:37:47.845 11744 11744 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9000, result=0, data=Intent { (has extras) }} to activity {org.oddb.generika/org.oddb.generika.MainActivity}: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
09-20 13:37:47.845 11744 11744 E AndroidRuntime: 	at org.oddb.generika.data.DataManager$2.execute(DataManager.java:154)
09-20 13:37:47.845 11744 11744 E AndroidRuntime: 	at org.oddb.generika.model.Retryable$-CC.withRetry(Retryable.java:55)
09-20 13:37:47.845 11744 11744 E AndroidRuntime: 	at org.oddb.generika.model.Product.withRetry(Product.java:170)
09-20 13:37:47.845 11744 11744 E AndroidRuntime: 	at org.oddb.generika.data.DataManager.addProduct(DataManager.java:149)
09-20 13:37:47.845 11744 11744 E AndroidRuntime: 	at org.oddb.generika.MainActivity.onActivityResult(MainActivity.java:660)
09-20 13:37:47.849  1732  8519 W ActivityTaskManager:   Force finishing activity org.oddb.generika/.MainActivity
09-20 13:37:47.853  1732  1804 I ActivityManager: Showing crash dialog for package org.oddb.generika u0
09-20 13:37:47.892  1732  1804 D CoreBackPreview: Window{2e9ceaf u0 Application Error: org.oddb.generika}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@60254fd, mPriority=0, mIsAnimationCallback=false}
09-20 13:37:48.352  1732  1806 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{b246d16 u0 org.oddb.generika/.MainActivity t75 f}}
09-20 13:37:48.352  1732  1806 W ActivityTaskManager: Activity pause timeout for ActivityRecord{b246d16 u0 org.oddb.generika/.MainActivity t75 f}}
09-20 13:37:48.425  1732  1803 V WindowManager:         {WCT{RemoteToken{6213620 Task{87244a2 #75 type=standard A=10301:org.oddb.generika}}} m=CLOSE f=NONE leash=Surface(name=Task=75)/@0x8591a52 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
09-20 13:37:48.757  1732 19643 V WindowManager: Loading animations: layout params pkg=org.oddb.generika resId=0x1030308
09-20 13:37:51.414  1732  1804 D CoreBackPreview: Window{2e9ceaf u0 Application Error: org.oddb.generika}: Setting back callback null
09-20 13:37:51.414  1732  8519 I ActivityManager: Killing 11744:org.oddb.generika/u0a301 (adj 900): crash
09-20 13:37:51.417  1732  8519 W InputManager-JNI: Input channel object '63c7fbd org.oddb.generika/org.oddb.generika.MainActivity (client)' was disposed without first being removed with the input manager!
09-20 13:37:51.420  1732  8519 W InputManager-JNI: Input channel object 'd3b5e6e org.oddb.generika/org.oddb.generika.BarcodeCaptureActivity (client)' was disposed without first being removed with the input manager!
09-20 13:37:51.433  1732  1804 W InputManager-JNI: Input channel object '2e9ceaf Application Error: org.oddb.generika (client)' was disposed without first being removed with the input manager!
09-20 13:37:51.537  1732  8519 V ActivityManager: Got obituary of 11744:org.oddb.generika
```

**Comment by zdavatz** [comment]
this did the trick: https://github.com/realm/realm-java/issues/7141#issuecomment-705025611
